tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install Django
      python manage.py migrate

      env:
        ENVIRONMENT: 'development'
        SENDGRID_PASSWORD: 123
        SENDGRID_USERNAME: user
        SECRET_KEY: '123'
        POSTGRES_HOST_AUTH_METHOD: trust
  - command: |
      source venv/bin/activate
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
