tasks:

  - name: Env variables
    env:
      ENVIRONMENT: 'development'
      SENDGRID_PASSWORD: 123
      SENDGRID_USERNAME: user
      SECRET_KEY: '123'
      POSTGRES_HOST_AUTH_METHOD: trust
      
  - command: |
      make dev_build
      make dev_web_exec cmd='python manage.py migrate'
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
