services:
  web:
    env_file:
      - .env
    build: .
    command: /bin/sh -c "uv sync --frozen --no-install-project && python /code/manage.py runserver 0.0.0.0:8000 --settings=core.settings.development"
    volumes:
      - .:/code
      - /code/.venv
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    env_file:
        - .env
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  postgres_data:
